// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA4PEF3lgdZf8mUPbzsbipQ23HcWP9vtdE',
    appId: '1:868440827001:web:ff190b234b2e5a788de0a8',
    messagingSenderId: '868440827001',
    projectId: 'volunteer-companion-app',
    authDomain: 'volunteer-companion-app.firebaseapp.com',
    storageBucket: 'volunteer-companion-app.firebasestorage.app',
    measurementId: 'G-ZCEXC4WBVV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA49OfxiBa00r_6CZ4JVWgGb9kWzKOTbpQ',
    appId: '1:868440827001:android:1475eca08c8708028de0a8',
    messagingSenderId: '868440827001',
    projectId: 'volunteer-companion-app',
    storageBucket: 'volunteer-companion-app.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCGPulMjOlDFPyGNVkkM6pmnaLo6BlfSu4',
    appId: '1:868440827001:ios:f36d791f9bbf715e8de0a8',
    messagingSenderId: '868440827001',
    projectId: 'volunteer-companion-app',
    storageBucket: 'volunteer-companion-app.firebasestorage.app',
    iosBundleId: 'com.example.volunteerCompanionApp',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCGPulMjOlDFPyGNVkkM6pmnaLo6BlfSu4',
    appId: '1:868440827001:ios:f36d791f9bbf715e8de0a8',
    messagingSenderId: '868440827001',
    projectId: 'volunteer-companion-app',
    storageBucket: 'volunteer-companion-app.firebasestorage.app',
    iosBundleId: 'com.example.volunteerCompanionApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA4PEF3lgdZf8mUPbzsbipQ23HcWP9vtdE',
    appId: '1:868440827001:web:252638fb9eead0528de0a8',
    messagingSenderId: '868440827001',
    projectId: 'volunteer-companion-app',
    authDomain: 'volunteer-companion-app.firebaseapp.com',
    storageBucket: 'volunteer-companion-app.firebasestorage.app',
    measurementId: 'G-017VRP02MT',
  );
}
